---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-09-18-21:46:06
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Joystick.View.JoystickMdr : Game.Core.Ioc.BaseMediator
local JoystickMdr = class("JoystickMdr",BaseMediator)

function JoystickMdr:OnInit()
    self.hotArea = self.gameObject:FindChild("HotArea")
    self.pan = self.gameObject:FindChild("Pan")
    self.stick = self.gameObject:FindChild("Stick")

    self.panRect = self.pan:GetRect()
    self.stickRect = self.stick:GetRect()
end

function JoystickMdr:RegisterListeners()
    self:AddObjectEventListener(LuaHelper.AddObjectPointerDown, self.hotArea,handler(self, self.OnHotAreaDown))
    self:AddObjectEventListener(LuaHelper.AddObjectDrag, self.hotArea,handler(self, self.OnHotAreaDrag))
    self:AddObjectEventListener(LuaHelper.AddObjectEndDrag, self.hotArea,handler(self, self.OnHotAreaDragEnd))
    self:AddObjectEventListener(LuaHelper.AddObjectPointerUp, self.hotArea,handler(self, self.OnHotAreaDragEnd))
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function JoystickMdr:OnHotAreaDown(eventData)
    self:OnHotAreaDrag(eventData)
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function JoystickMdr:OnHotAreaDrag(eventData)
    local position = eventData.pointerCurrentRaycast.worldPosition
    position = Tools.WorldToUILocalPosition( self.uiCamera, position)
    self.panRect.position = position
    self.stickRect.position = position
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function JoystickMdr:OnHotAreaDragEnd(eventData)

end

return JoystickMdr
