---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:59
---

local WeaponBase = require("Game.Modules.Battle.Weapon.WeaponBase")

---@class Game.Modules.Battle.Weapon.WeaponDefault : Game.Modules.Battle.Weapon.WeaponBase
---@field New fun(ecsWorld:Game.ECSWorld)
local WeaponDefault = class("Game.Modules.Battle.Weapon.WeaponDefault", WeaponBase)

---@param ecsWorld Game.ECSWorld
function WeaponDefault:Ctor(ecsWorld)
    WeaponDefault.super.Ctor(self, ecsWorld)

    local weaponInfo = self:CreateWeaponInfo()
    --1级武器
    weaponInfo.BulletEuler = Vector3.New(90, 180, 0)
    weaponInfo.BulletGap = -0.1
    weaponInfo.BulletBlastDuration = 0.2
    weaponInfo.ShootDir = Vector3.New(0, 0, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo = self:CreateWeaponInfo()
    weaponInfo.BulletEuler = Vector3.New(90, 180, 0)
    weaponInfo.BulletGap = 0.1
    weaponInfo.BulletBlastDuration = 0.2
    weaponInfo.ShootDir = Vector3.New(0, 0, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
end

---@return Game.WeaponInfo
function WeaponDefault:CreateWeaponInfo()
    local weaponInfo = Game.WeaponInfo.New()
    weaponInfo.No = 0
    weaponInfo.Level = 0
    weaponInfo.Damage = math.random(10, 30)
    weaponInfo.ShootOffset = 0.7
    weaponInfo.BulletSpeed = 30
    weaponInfo.BulletScale = Vector3.New(0.3, 1, 1)
    return weaponInfo
end

return WeaponDefault