---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:28
---

local WeaponBase = require("Game.Modules.Battle.Weapon.WeaponBase")

---@class Game.Modules.Battle.Weapon.WeaponNo1 : Game.Modules.Battle.Weapon.WeaponBase
---@field New fun(ecsWorld:Game.ECSWorld)
local WeaponNo1 = class("Game.Modules.Battle.Weapon.WeaponNo1", WeaponBase)

---@param ecsWorld Game.ECSWorld
function WeaponNo1:Ctor(ecsWorld)
    WeaponNo1.super.Ctor(self, ecsWorld)

    local weaponInfo = self:CreateWeaponInfo()
    --1级武器
    weaponInfo.Level = 1
    weaponInfo.BulletEuler = Vector3.New(90, 168.75, 0)
    weaponInfo.ShootDir = Vector3.New(-0.125, 0, 0.5)
    weaponInfo.BulletGap = -0.1
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = -0.3
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.BulletEuler = Vector3.New(90, 191.25, 0)
    weaponInfo.ShootDir = Vector3.New(0.125, 0, 0.5)
    weaponInfo.BulletGap = 0.1
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = 0.3
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    --二级武器
    weaponInfo.Level = 2
    weaponInfo.BulletEuler = Vector3.New(90, 157.5, 0)
    weaponInfo.ShootDir = Vector3.New(-0.25, 0, 0.5)
    weaponInfo.BulletGap = -0.5
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    weaponInfo.BulletGap = -0.7
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.BulletEuler = Vector3.New(90, 202.5, 0)
    weaponInfo.ShootDir = Vector3.New(0.25, 0, 0.5)
    weaponInfo.BulletGap = 0.5
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    weaponInfo.BulletGap = 0.7
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    --三级武器
    weaponInfo.Level = 3
    weaponInfo.BulletEuler = Vector3.New(90, 157.5, 0)
    weaponInfo.ShootDir = Vector3.New(-0.25, 0, 0.5)
    weaponInfo.BulletGap = -0.5
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    weaponInfo.BulletGap = -0.7
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.BulletEuler = Vector3.New(90, 202.5, 0)
    weaponInfo.ShootDir = Vector3.New(0.25, 0, 0.5)
    weaponInfo.BulletGap = 0.5
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    weaponInfo.BulletGap = 0.7
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
end

---@return Game.WeaponInfo
function WeaponNo1:CreateWeaponInfo()
    local weaponInfo = Game.WeaponInfo.New()
    weaponInfo.No = 1
    weaponInfo.Damage = math.random(10, 30)
    weaponInfo.ShootOffset = 0.7
    weaponInfo.BulletSpeed = 30
    weaponInfo.BulletScale = Vector3.New(0.3, 1, 1)
    return weaponInfo
end

return WeaponNo1